spring:
  application:
    name: backend
  jackson:
    time-zone: Asia/Seoul
  datasource:
    url: jdbc:mysql://localhost:3306/${DATABASE_NAME}?serverTimezone=Asia/Seoul
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: ${LOCAL_DDL_TYPE}

#logging:
#  level:
#    org:
#      springframework: debug

api:
  key: ${API_KEY}
